import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "./components/Navigation";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <header className="main-header">
        <Navigation/>
        </header>
        <main className="main-content">
          {children}
        </main>
        <footer className="main-footer">
          <p>© {new Date().getFullYear()} Ezzaldeen Albitar. All rights reserved.</p>
        </footer>
      </body>
    </html>
  );
}
